title: Kartikeya Arora - Physics PhD Student
description: Physics PhD student at USC specializing in quantum computing research
url: "https://arora-kartikeya.github.io"
baseurl: ""

author:
  name: Kartikeya Arora
  email: kartikeya@usc.edu

# SEO settings
google_analytics: GA_TRACKING_ID
google_site_verification: YOUR_VERIFICATION_CODE

# Social media
social:
  github: arora-kartikeya
  google_scholar: YOUR_SCHOLAR_ID
  orcid: YOUR_ORCID_ID
  linkedin: YOUR_LINKEDIN_PROFILE

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
